---
date: "`r lubridate::today('US/Pacific')`"
author: "Arturo Lopez Pineda"
title: "Medication Alignment Algorithm (Medal)"
output: rmarkdown::github_document
code_folding: hide
df_print: default
editor_options: 
  chunk_output_type: console
---

# Step 0. Load required libraries

```{r, load-libraries}

remove(list=ls())

#General
library(tidyverse)
library(here)
library(dplyr)
library(knitr)

#Plotting libraries
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(ggplotify)

#Clustering libraries
library(factoextra)
library(NbClust)
library(aricode)
library(Rtsne)
library(dendextend)
library(NMF) #for cluster purity and entropy

#Heatmap
library("pheatmap")

#Additional functions
#source(here("programs", "fun-medal.R")) #PyMedal is used instead
source(here("programs", "fun-support.R"))
source(here("programs", "fun-plot.R"))

```

\  

# Step 1. Read file

```{r, read-files}

#---
#File with patient ID (de-ID), comorbidities, initial clinical presentation, etc.
patients.og <- read_csv(here("../data", "patients.csv")) %>%
  column_to_rownames(var="id") 

#Select only a few columns
patients <- patients.og %>%
  select("age_onset", "age_1st_appt", "is_male", "NHW", "OCD", "foodprob", "anx", 
            "emotional", "mood", "agg", "sch", "reg", "sleep", "tics") %>%
  drop_na()

#---
#File with events
events.og <- read_csv(here("../data", "medications.csv")) 

#Select only events related to patients in the previous file
events <- events.og %>%
  filter(id %in% rownames(patients)) %>%
  select("id", "medication", "start", "end")

#---
#File with clinical evaluations (outcomes)
outcomes.og <- read_csv(here("../data","outcomes.csv"))

#Select only rows for the same patients listed in Profiles
outcomes <- outcomes.og %>%
  filter(id %in% rownames(patients)) %>%
  select("id", "gi_new", "cbiTotal", "daysSinceBirth")

#---
#Censoring
years = 2

```

\ 

# Step 2. Clean Data and Right Censor
```{r, clean-data}

# Group by class of medication
medgroups <- lst(penicillin = c("penicillin v", "penicillin g", "amoxicillin", "augmentin"),
                cephalosporin = c("cephalexin", "cefadroxil"), 
                macrolide = c("azithromycin"),
                nsaid = c("ibuprofen", "naproxen", "indomethacin", "sulindac", "aspirin"),
                corticosteroid.oral = c("prednisone", "maintenance prednisone", "decadron"),
                corticosteroid.iv = c("solumedrol"),
                immunoglobulins = c("ivig"),
                dmard = c("rituximab", "methotrexate", "cellcept"))

medcolors= c("penicillin"="#66c2a5",
             "cephalosporin" = "#fc8d62",
             "macrolide" = "#8da0cb",
             "nsaid" = "#e7298a",
             "corticosteroid.oral" = "#a6d854",
             "corticosteroid.iv" = "#ffd92f",
             "antibody" = "green",
             "immunoglobulins" = "#e5c494",
             "dmard" = "#b3b3b3")


events <- events.og %>%
  cleanEvents(medgroups) %>%
  rightCensoring(years)

write_csv(events, here("../data", "data-matrix-clean.csv"))

```

\  

# Step 3. Create a distance matrix
```{r, call-medal}

#-------
#Calling pyMEDAL

pymedal <- here("pymedal", "pymedal.py")
input <- here("../data", "data-matrix-clean.csv")

system(paste('python3', pymedal, input), wait=TRUE)


#Reading the output
distMatrix = read.table("distance_mat.txt")
patientIDs = read.table("patientID.txt", sep=",")

pID = as.vector(unlist(patientIDs))
colnames(distMatrix) = pID
rownames(distMatrix) = pID

```

\  

# Step 4 Choose number of clusters

```{r, num-clusters}

d = distMatrix

# Elbow method
elbow <- fviz_nbclust(x=d, diss=as.dist(d), hcut, method = "wss") +
  #geom_vline(xintercept = k, linetype = "dashed", color="#5581B0", size=0.6) +
  labs(title = "Elbow method",
       y="Total within-clusters sum of squares") +
  theme_light()

# Silhouette method
silhouette <- fviz_nbclust(x=d, diss=as.dist(d), hcut, method = "silhouette", 
                           print.summary = FALSE, barcolor = "white") +
  #geom_vline(xintercept = 2, linetype = "dashed", color="#5581B0", size=0.6) +
  #geom_vline(xintercept = 4, linetype = "dashed", color="#5581B0", size=0.6) +
  labs(title = "Silhouette method") +
  theme_light()


# Gap statistic
# nboot = 50 to keep the function speedy. 
# recommended value: nboot= 500 for your analysis.
# Use verbose = FALSE to hide computing progression.
set.seed(123)
gapStat <- fviz_nbclust(x=d, diss=as.dist(d), hcut, nstart = 25, 
                        method = "gap_stat", nboot = 50, print.summary = TRUE,
                        maxSE=list(method="Tibs2001SEmax", SE.factor=1)) +
  labs(title = "Gap statistic method") +
  theme_light()

clest <- fviz_nbclust(x=d, diss=as.dist(d), hcut, nstart = 25, 
                        method = "gap_stat", nboot = 50, print.summary = TRUE,
                        maxSE=list(method="globalSEmax", SE.factor=3)) +
  labs(title = "Clest method") +
  theme_light()

numKPanels <- ggarrange(elbow, silhouette, gapStat, clest,
                     labels = c("A", "B", "C", "D"),
                     ncol = 2, nrow = 2, legend="bottom", 
                     align="v", common.legend = FALSE)
ggexport(numKPanels, filename=here("images", "Figure1-num-clusters.png"), height = 2500, width = 3000, res=300)

gpanels



```

\ 

# Step 5. Plot clusters

```{r, plot-clusters}

k=6
set.seed(123)

#Colors to be used
#colors.hclust <- c("1"="#a6cee3", "2"="#ff7f00", "3"="#b2df8a", 
#                   "4"="#6a3d9a", "5"="#fcbba1", "6"="#e31a1c")
#colors.kmeans <- c("1"="#fdbf6f", "2"="#1f78b4", "3"="#cab2d6", 
#                   "4"="#33a02c", "5"="#fb9a99", "6"="#b15928")

colors.hclust <- c("1"="#1b9e77", "2"="#7570b3", "3"="#e6ab02", 
                   "4"="#d95f02", "5"="#a6761d", "6"="#e7298a")
colors.kmeans <- c("1"="#e6ab02", "2"="#d95f02", "3"="#e7298a", 
                   "4"="#a6761d", "5"="#7570b3", "6"="#1b9e77")




#Plot Clustering strategies
dend = getDendrogram(d, k, colors.hclust)
gDend <- plotDendrogram(dend, k)
gMDSclus12 <- plotMDS(d, as.character(cutree(dend, k)), colors.hclust, 1, 2, "Hierarchical clustering (hclust)")
#gMDSclus34 <- plotMDS(d, as.character(cutree(dend, k)), colors.hclust, 3, 4, "MDS (hierarchical clustering)")

kmeans = getKMeansClusteringPCA(d, k)
gMDSkmeans12 <- plotMDS(d, kmeans$cluster, colors.kmeans, 1, 2, "K-means")
#gMDSkmeans34 <- plotMDS(d, kmeans$cluster, colors.kmeans, 3, 4, "MDS (k-means)")


#TSNE
tsne1 = as.data.frame(Rtsne(d, perplexity=4, is_distance=TRUE, initial_dims=5, theta=0)$Y)

tsne2 = getHierarchicalClusteringTSNE(d, k, tsne1)
gTSNEclus <- plotTSNE(tsne2, colors.hclust, "TSNE (hierarchical clustering)")
 
tsne3 = getKMeansClusteringTSNE(d, k, tsne1)
gTSNEkmeans <- plotTSNE(tsne3, colors.kmeans, "TSNE (k-means)")


#Combine plots and save
gpanels <- ggarrange(gDend,
                     ggarrange(gMDSclus12, gTSNEclus,
                               labels = c("B", "C"),
                               align = "hv",
                               legend="bottom", common.legend = TRUE),
                     ncol = 1, nrow=2,
                     labels = c("A"),
                     align = "h",
                     legend="bottom", common.legend = TRUE)
ggexport(gpanels, filename=here("images", "Figure2-a-dendro-mds.png"), height = 4000, width = 4000, res=300)

#gpanels


gpanels <- ggarrange(ggarrange(gMDSkmeans12, gTSNEkmeans,
                               align = "h",
                               legend="bottom", common.legend = TRUE),
                     ggarrange(gMDSclus12, gTSNEclus,
                               align = "h",
                               legend="bottom", common.legend = TRUE),
                     ncol = 1, nrow=2,
                     labels = c("A", "B"),
                     align = "h",
                     legend="bottom", common.legend = FALSE)
ggexport(gpanels, filename=here("images", "Figure2-b-dendro-mds.png"), height = 4000, width = 4000, res=300)


kmeans_annot <- as.data.frame(kmeans["cluster"]) %>%
  rename(kmeans=cluster)
hclust_annot <- as.data.frame(factor(cutree(dend,k))) %>%
  rename(hclust = colnames(.)[1])
ann_colors <- list(kmeans = colors.kmeans, hclust = colors.hclust)


gHeatMap <- as.ggplot(pheatmap(d, cutree_cols = 6, cutree_rows = 6,
                    scale="none",
                    show_colnames = TRUE,
                    show_rownames = TRUE,
                    clustering_distance_rows = "minkowski",
                    clustering_distance_cols = "minkowski",
                    clustering_method = "ward.D",
                    labels_col = paste0(rownames(d)),
                    labels_row = paste0(rownames(d)),
                    annotation_col = kmeans_annot,
                    annotation_row = hclust_annot,
                    annotation_colors = ann_colors,
                    legend = TRUE,
                    cluster_rows = TRUE,
                    cluster_cols = TRUE))
  


# Combine plots and save
gpanels <- ggarrange(gHeatMap, 
                     ggarrange(gMDSclus12, gMDSkmeans12,
                               labels = c("B", "C"),
                               align = "hv",
                               ncol = 2, nrow=1, 
                               legend="bottom", common.legend = FALSE),
                     labels = c("A", ""),
                     align = "hv",
                     ncol = 1, nrow=2)

ggexport(gpanels, filename=here("images", "Figure2-heatmap-mds.png"), height = 4000, width = 3000, res=300)

```

\ 

# Step 6. Comparison to K-means

```{r, comparison}

NMI <- c()
Entropy <- c()
Purity <- c()

for(i in 1:10){
  kmeans = getKMeansClusteringPCA(d, i)$cluster
  hclust = cutree(getDendrogram(d, i, colors.hclust), i)
  
  #Calculating Normalized Mutual Information
  #https://course.ccs.neu.edu/cs6140sp15/7_locality_cluster/Assignment-6/NMI.pdf
  NMI = c(NMI, round(NMI(kmeans, hclust, variant="sum"), digits=2))
  
  #Calculating Cluster purity
  #https://www.rdocumentation.org/packages/NMF/versions/0.21.0/topics/purity
  Purity = c(Purity, round(purity(kmeans, hclust), digits=2))
  
  #Calculating Cluster entropy
  #https://www.rdocumentation.org/packages/NMF/versions/0.21.0/topics/purity
  Entropy = c(Entropy, round(entropy(kmeans, hclust), digits=2))

}

#Print table
results <- as.data.frame(cbind(k=c(1:10), NMI, Purity, Entropy))

results %>%
  kable()

res <- bind_rows(results %>% 
                   select(k, value=NMI) %>% 
                   mutate(Test="NMI"),
                 results %>% 
                   select(k, value=Purity) %>% 
                   mutate(Test="Purity"),
                 results %>% 
                   select(k, value=Entropy) %>% 
                   mutate(Test="Entropy"))
  

clus.test <- ggplot(res, aes(x=k, y=value, group=Test, color=Test)) +
  geom_vline(xintercept=6, color="gray30", linetype="dashed", size=1.5) +
  geom_point(size=2.5) +
  geom_line(size=1) +
  #geom_vline(xintercept=7, color="gray40", linetype="dashed") +
  scale_colour_manual(values=c("#7fc97f", "#beaed4", "#fdc086")) +
  scale_x_continuous(limits=c(1,10), breaks=c(0:10)) +
  ggtitle("Comparison between K-means and Hierarchical Clustering")+
  theme_light() +
  theme(legend.position = "bottom")

gpanel <- ggarrange(numKPanels, clus.test,
                    labels = c("", "E"),
                     align = "h",
                     ncol = 1, nrow=2)

ggexport(gpanel, filename=here("images", "Figure3-metrics.png"), height = 3600, width = 2000, res=300)


```

\ 

# Step 7. Save cluster assignment

```{r, save-cluster}


#Saving the cluster to profiles
assignment <- hclust_annot
assignment <- kmeans_annot
#index = which(profiles$id %in% names(assignment))
#write.csv(cbind(profiles[index,], cluster=assignment),
#          "../data/data-matrix-profiles-cluster.csv")

profiles <- patients %>%
  rownames_to_column(var="id") %>%
  filter(id %in% rownames(assignment)) %>%
  mutate(cluster=unlist(assignment))

```

\ 


# Step 8. Evaluate clusters

```{r, evaluate-cluster}

source(here("programs", "fun-plot.R"))

#Get all paths
gPath1 <- plotTimeSeriesDrug(1, events, profiles, medcolors, medgroups, years)
gPath2 <- plotTimeSeriesDrug(2, events, profiles, medcolors, medgroups, years)
gPath3 <- plotTimeSeriesDrug(3, events, profiles, medcolors, medgroups, years)
gPath4 <- plotTimeSeriesDrug(4, events, profiles, medcolors, medgroups, years)
gPath5 <- plotTimeSeriesDrug(5, events, profiles, medcolors, medgroups, years)
gPath6 <- plotTimeSeriesDrug(6, events, profiles, medcolors, medgroups, years)



#Get all impairment scores
gGIS1 <- plotScores(1, outcomes, "gi_new", c(0,100,5), profiles, 2, "gray50", "Global Impairment", TRUE, FALSE)
gGIS2 <- plotScores(2, outcomes, "gi_new", c(0,100,5), profiles, 2, "gray50", "Global Impairment", TRUE, FALSE)
gGIS3 <- plotScores(3, outcomes, "gi_new", c(0,100,5), profiles, 2, "gray50", "Global Impairment", TRUE, FALSE)
gGIS4 <- plotScores(4, outcomes, "gi_new", c(0,100,5), profiles, 2, "gray50", "Global Impairment", TRUE, FALSE)
gGIS5 <- plotScores(5, outcomes, "gi_new", c(0,100,5), profiles, 2, "gray50", "Global Impairment", TRUE, FALSE)
gGIS6 <- plotScores(6, outcomes, "gi_new", c(0,100,5), profiles, 2, "gray50", "Global Impairment", TRUE, FALSE)
   
gcbi1 <- plotScores(1, outcomes, "cbiTotal", c(0,96,4), profiles, 2, "gray50", "Caregiver Burden", TRUE, TRUE)
gcbi2 <- plotScores(2, outcomes, "cbiTotal", c(0,96,4), profiles, 2, "gray50", "Caregiver Burden", TRUE, TRUE)
gcbi3 <- plotScores(3, outcomes, "cbiTotal", c(0,96,4), profiles, 2, "gray50", "Caregiver Burden", TRUE, TRUE)
gcbi4 <- plotScores(4, outcomes, "cbiTotal", c(0,96,4), profiles, 2, "gray50", "Caregiver Burden", TRUE, TRUE)
gcbi5 <- plotScores(5, outcomes, "cbiTotal", c(0,96,4), profiles, 2, "gray50", "Caregiver Burden", TRUE, TRUE)
gcbi6 <- plotScores(6, outcomes, "cbiTotal", c(0,96,4), profiles, 2, "gray50", "Caregiver Burden", TRUE, TRUE)



#Save plot
gpanels <- ggarrange(gPath1, gPath2, gPath3, gPath4, gPath5, gPath6,
                     gGIS1, gGIS2, gGIS3, gGIS4, gGIS5, gGIS6,
                     gcbi1, gcbi2, gcbi3, gcbi4, gcbi5, gcbi6,
                     #labels = c("Clus1", "Clus2", "Clus3", "Clus4", "Clus5", "Clus6"),
                     heights = c(6,1,1),
                     align = "hv",
                     ncol = 6, nrow = 3, legend="none", common.legend = FALSE)
ggexport(gpanels, filename=here("images", "Figure3-clusters.png"),
         height = 4000, width = 5000, res=300)



```

\ 